config/routes.rb
Rails.application.routes.draw do
  get 'max_view(/:date)(.:format)' => 'skill#max'
  get 'musics(/:date)(.:format)' => 'music#index'
  resources :list, only: [:index]
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  @@mode = :cxb

  def self.mode=(mode)
    @@mode = mode
  end

  def self.music_diffs
    MUSIC_DIFFS[@@mode]
  end

  protected
  def mode
    @@mode
  end

  def music_diffs
    ApplicationRecord.music_diffs
  end

  def valid_diff?(diff)
    music_diffs.keys.include? diff
  end
end

app/models/monthly.rb
class Monthly < ApplicationRecord
  belongs_to :music
end

app/models/music.rb
class Music < ApplicationRecord
  @@pivot = nil

  has_one :monthly, -> do
    where 'span_s <= ? and span_e > ?', @@pivot || Time.now, @@pivot || Time.now
  end

  def self.pivot=(pivot)
    @@pivot = pivot
  end

  def self.find_actives
    musics = Music.where(activated: true)
    if @@pivot
      musics = musics.where('added_at <= ?', @@pivot)
    end
    musics
  end

  def level(diff)
    valid_diff?(diff) ? send("level#{diff}") : nil
  end

  def notes(diff)
    valid_diff?(diff) ? send("notes#{diff}") : nil
  end

  def monthly?
    monthly.present?
  end

  def deleted?
    @@pivot ? (deleted_at.present? && deleted_at < @@pivot) : deleted
  end

  def max_diff
    max_diff = nil
    music_diffs.keys.sort.reverse.each do |diff|
      next unless level(diff)
      max_diff = diff
      break
    end
    max_diff
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  belongs_to :music
  include Comparable

  def maximize!
    max_diff = music.max_diff
    send("stat#{max_diff}=", SKILL_STAT_CLEARED)
    send("rate#{max_diff}=", 100.0)
    send("gauge#{max_diff}=", gauges.keys.max)
    send("combo#{max_diff}=", SKILL_COMBOS_ALL.keys.max)
    calc!
  end

  def stat(diff)
    valid_diff?(diff) ? send("stat#{diff}") : nil
  end

  def point(diff)
    valid_diff?(diff) ? send("point#{diff}") : nil
  end

  def rate(diff)
    valid_diff?(diff) ? send("rate#{diff}") : nil
  end

  def gauge(diff)
    valid_diff?(diff) ? send("gauge#{diff}") : nil
  end

  def combo(diff)
    valid_diff?(diff) ? send("combo#{diff}") : nil
  end

  def locked(diff)
    valid_diff?(diff) ? send("locked#{diff}") : nil
  end

  def calc!
    changed = false
    music_diffs.keys.each do |diff|
      next unless music.level(diff)
      if diff_changed?(diff)
        level = music.level(diff)
        bonus_rate = SKILL_GAUGE_BONUS_RATES[gauge(diff)]
        if send("point#{diff}_changed?")
          send("rate#{diff}=", BigDecimal.new((point(diff) / bonus_rate).to_s).ceil(2) / level).floor(2) * 100
          send("rate_f#{diff}", false)
          changed = true
        else
          send("point#{diff}=", BigDecimal.new((level * (rate(diff).to_i / 100.0) * bonus_rate).to_s).floor(2))
          changed = true
        end
      end
    end

    if changed
      self.best_point = 0.00
      self.l_best_point = 0.00
      music_diffs.keys.sort.each do |diff|
        if point(diff)
          if !locked(diff) and point(diff) >= best_point
            self.best_point = point(diff)
            self.best_diff = diff
          end
          if point(diff) >= l_best_point
            self.l_best_point = point(diff)
            self.l_best_diff = diff
          end
        end
      end
    end
  end

  def <=>(other)
    best_point <=> other.best_point
  end

  private
  def gauges
    SKILL_GAUGES[self.mode]
  end

  def diff_changed?(diff)
    send("rate#{diff}_changed?") || send("point#{diff}_changed?") || send("gauge#{diff}_changed?")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
  def index
    Music.mode = SITE_MODE
    Music.pivot = Date.parse(params[:date]) if params[:date]
    musics = Music.find_actives.order(:number)

    @music_set = {deleted: [], normal: [], monthly: []}
    musics.each do |music|
      if music.deleted?
        @music_set[:deleted] << music
      elsif music.monthly?
        @music_set[:monthly] << music
      else
        @music_set[:normal] << music
      end
    end
  end
end

app/controllers/skill_controller.rb
class SkillController < ApplicationController
  def max
    Skill.mode = SITE_MODE
    Music.pivot = Date.parse(params[:date]) if params[:date]
    musics = Music.find_actives

    @skill_set = {normal: [], monthly: []}
    max_user = User.new
    musics.each do |music|
      next if music.deleted?
      skill = Skill.new(user: max_user, music: music)
      skill.maximize!

      if skill.music.monthly?
        @skill_set[:monthly] << skill
      else
        @skill_set[:normal] << skill
      end
    end
    @skill_set.each do |k, v|
      v.sort!.reverse!
      if k == :normal
        @skill_set[k] = @skill_set[k][0, 20]
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/skill_helper.rb
module SkillHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

%p= link_to 'Musics', 'musics'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Workspace
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p{style: 'text-align: right'}
      - if user_signed_in?
        = link_to sprintf('%05d', current_user.id), list_index_path
        = '/'
        = link_to 'Sign out', destroy_user_session_path, method: :delete
      - else
        = link_to 'Sign up', new_user_registration_path
        = '/'
        = link_to 'Sign in', new_user_session_path
    = yield

app/views/music/_list.html.haml
- if musics.size > 0
  %h2= section
  %table
    %thead
      %tr
        %th #
        %th title
        - Music.music_diffs.keys.sort.each do |diff|
          %th{colspan: 2}= Music.music_diffs[diff]
    %tbody
      - musics.each do |music|
        %tr
          %th= music.number
          %td= raw music.title
          - Music.music_diffs.keys.sort.each do |diff|
            %td= music.level(diff)
            %td= music.notes(diff)

app/views/music/index.html.haml
%h1 Music#index
%p Find me in app/views/music/index.html.haml

= render 'music/list', musics: @music_set[:monthly], section: 'Monthly'
= render 'music/list', musics: @music_set[:normal], section: 'Normal'
= render 'music/list', musics: @music_set[:deleted], section: 'Deleted'

app/views/skill/_list.html.haml
- if skills.size > 0
  %h2= section
  %table
    %thead
      %tr
        %th #
        %th title
        %th level
        %th point
        %th rate
        %th combo
    %tbody
      - skills.each do |skill|
        %tr
          %th= skill.music.number
          %td= raw skill.music.title
          %td= "[#{Skill.music_diffs[skill.best_diff]}] #{skill.music.level(skill.best_diff)}"
          %td= sprintf("%.2f", skill.point(skill.best_diff))
          %td= "#{skill.rate(skill.best_diff)} %"
          %td= SKILL_COMBOS_ALL[skill.combo(skill.best_diff)]

app/views/skill/max.html.haml
%h1 Skill#max
%p Find me in app/views/skill/max.html.haml

= render 'skill/list', skills: @skill_set[:monthly], section: 'Monthly'
= render 'skill/list', skills: @skill_set[:normal], section: 'Normal'